### ISSUE TITLE
Pressing 'U'/'R' on items in storage

### ISSUE THREAD

**Issue by aNinjin** [tom5454/Toms-Storage#114]
Pressing 'U'/'R' on items in storage will not bring up the corresponding window with REI (I haven't tested JEI).

**Comment by e-SonOfAnder** [comment]
This is due to the search field in the Crafting / Storage terminals forcing themselves to be active at all times when open, preventing JEI/REI from catching the keypresses. In addition to this, you will notice that even if you click away into the JEI search bar directly, you cannot type there, as the Tom's Storage terminal refuses to relinquish control. Definitely a bug that would be a huge boon to functionality if it were fixed.

**Comment by tpwrules** [comment]
I've run into this problem as well. It would be great if the search bar were selected by default, but you could click outside of it to deselect it. That's how the "auto" function works in similar mods.
