### ISSUE TITLE
Mixing Filtered and Unfiltered Cable Connectors Bug

### ISSUE THREAD

**Issue by srob650** [tom5454/Toms-Storage#156]
First of all, I love the mod, thanks for your work!

This seems to happen specifically when first loading the chunks where there are both filtered and unfiltered cable connectors on a system.

1. Have an inventory hopper feed an inventory connector
2. Use cable to connect that inventory connector to a line of chests
3. First set of chests use filtered cable connectors to sort drops from a farm
4. Final chest in the line uses an unfiltered chest into an open crate in order to dump drops that aren't wanted

This works great, but when unloading and reloading the area, the system seems to prefer the unfiltered cable connector first and then dumps all items, instead of first going through the filtered connectors.  Simply breaking and re-placing the unfiltered cable connector seems to fix it, but it's a hassle to have to do that every time.

I would love to know if there is a better way to achieve what I am doing, however this way is fine if the bug gets fixed!

**Comment by lesteenman** [comment]
It seems like the priority of the link cables, filtered or unfiltered, depends on the order in which they are loaded or placed. Items are always placed in the earliest placed link cable that's valid if I place all my link cables without logging in or out.

I haven't been able to consistently reproduce the order changing because of the area loading/unloading, but I have a feeling like the chunk that is loaded earliest will be prioritized when finding an inventory to place items in.

This lack of deterministic prioritization is the one thing that keeps me away from using the mod at the moment, as I'm hoping to have mostly sorted chests, with a few "overflow" chests for unsorted items. As it stands, you can only determine what ends up in what chest if you filter every chest.

I absolutely love the look and feel of the mod apart from the lack of prioritization!

**Comment by frdmn** [comment]
Just ran into this issue as well. Is there a workaround other than building everything into one chunk? This is quite a limiting factor for me right now.
