### ISSUE TITLE
[1.5.0] (1.19.2/3) Unable to remove items from terminal with EMI active.

### ISSUE THREAD

**Issue by Kai-mbe** [tom5454/Toms-Storage#200]
Adding items is fine.
Works fine after disabling EMI with ctrl + o.
Works in 1.4.6

I have unbound left and right click from EMI. Disabled Batch Renderer in EMI.

[latest.log](https://github.com/tom5454/Toms-Storage/files/10795836/latest.log)

**Comment by Redd56** [comment]
can confirm as well.

**Comment by emilyploszaj** [comment]
There is a bug in the EMI implementation here and in other version implementations of EMI I assume. this should be making an unclickable EmiStackInteraction by passing `(stack, null, false)` instead of just `(stack)`.
https://github.com/tom5454/Toms-Storage/blob/master/Toms-Storage-Fabric-1.19/src/loader-shared/java/com/tom/storagemod/emi/EMIPlugin.java#L25
