### ISSUE TITLE
Crafting terminal shows double the amount of items actually stored. (Visual bug)

### ISSUE THREAD

**Issue by Juresuper** [tom5454/Toms-Storage#22]

**Comment by tom5454** [comment]
What version are you using, forge or fabric?

**Comment by Fogrits** [comment]
Verify if you have an inventory connector (block version) touching a chest that has an inventory connector (in pipe form) attached

**Comment by jarn123** [comment]
![2021-02-28_13 45 27](https://user-images.githubusercontent.com/69686962/109418975-4f425000-79cb-11eb-9e53-a064b5e78c19.png)
I had also that it showed double in a normal terminal

**Comment by tom5454** [comment]
You connected the same chest twice, the Inventory Connector will link through all touching inventories, so your chests don't need to touch the inventory connector directly (this is a config option, which is enabled by default).

**Comment by homemmakako** [comment]
This actually happens when using double chests from `Expanded Storage`. I imagine `TSS` checks for the contents of the first chest of the pair, the chest returns the content of both chests. TSS then goes on to checking the contents of the segund chest of the pair, which, again, returns the contents of both chests, resulting in item number appearing as 2x the real value.

### Player Solutions:
- If you are using `Expanded Storage` you can just disconect the chests, so they behave as single chests and let `TSS` add up the contents individually
- Another option is to use double chests directly connected to the network and disable the options to check for connected inventories in the config.

As for the bug solution, if my theory is correct, there might not be a good way to solve it as any mods that have connected inventory blocks will have a similar problem. For `Expanded Storage` you can possibly check for the `type` property of the chest, but that would only be adding an exception, and the problem would arise when interacting with other mods. I feel like the better solution would be to move the "check for connected inventories" option from the config file to the connectors, so players can right click or open a gui to choose how that specific connector would work.
