### ISSUE TITLE
[1.21 Fabric] Terminals not displaying items when attached to inventory connector.

### ISSUE THREAD

**Issue by J4gm** [tom5454/Toms-Storage#420]
I have a standard starting setup with an inventory connector adjacent to a set of vanilla chests and a crafting terminal on the inventory connector. I can deposit items into the terminal and they go into the chests as intended but I cannot see or withdraw the items in the network from the terminal. The issue affects both types of terminal. They can still interact with single inventories just fine, this only happens when they are attached to the inventory connector. I replicated the issue in a fresh install with no other mods. This appears to only be an issue on the new version 2.0.7. Downgrading to 2.0.6 repaired the issue for me.

Minecraft 1.21
Fabric 0.16.0
Tom's 2.0.7

Love the mod! Keep up the good work.

**Comment by tom5454** [comment]
Can you post a screenshot of your setup?

**Comment by Edgeburn** [comment]
I am having the same issue, same versions.

This setup is not working, where it did on the previous version
![2024-07-18_22 42 06](https://github.com/user-attachments/assets/39d50b6f-2a55-4fbf-aff7-ccdc6c973742)

When I right-click on an inventory connector, it still shows the same number of containers
![2024-07-18_22 46 11](https://github.com/user-attachments/assets/805ea1c4-c5e2-43f7-887b-219f34197ed6)



However, this setup does appear to still be functional
![2024-07-18_22 44 16](https://github.com/user-attachments/assets/cacc7e06-6859-44d0-9052-f79f39bc38ca)

**Comment by J4gm** [comment]
> Can you post a screenshot of your setup?

Inventory connector with some items in the chests:
![image](https://github.com/user-attachments/assets/9999f360-6da5-4300-b5d5-afb2fdbbc2f1)
No items showing up in the terminal:
![image](https://github.com/user-attachments/assets/504810d3-4146-4715-bc2f-2fc343b9c0c6)

**Comment by maxheyn** [comment]
Also having the same problem.

**Comment by appletechgeek** [comment]
Same issue here, suddenly items are not showing up in inventory anymore 
![image](https://github.com/user-attachments/assets/976a563b-9e08-4142-868f-43c33920d1f5)

**Comment by appletechgeek** [comment]
![image](https://github.com/user-attachments/assets/8fb5fc53-20ca-4bf7-82ef-fe7cae6357d6)
downgrading back to the version released prior to the one from july 17th fixes the issue for now

**Comment by DecayingEagle** [comment]
I just got the same issue. Yesterday I set it up, I had no problems, wireless terminal worked as well, before I went to bed I was doing something with mods and updated all of them. Today I come back and it does flash. This was my setup (before I noticed that this won't work anyways)

![image](https://github.com/user-attachments/assets/991a0dc2-4369-449f-9fd3-bbe84a994a7d)


After some more testing I noticed that it is doing something weird so before I had a setup like this

![image](https://github.com/user-attachments/assets/110c41c9-a69c-47d1-b2d5-e0f9ba11f661)

And now when I have the current setup it's jumping between these three states:
![image](https://github.com/user-attachments/assets/9cf0b5e2-2a80-4a43-8173-7936e7e79b30)
![image](https://github.com/user-attachments/assets/a699c4f8-e8b9-4f24-99e9-70e7647cd2a4)
and blank (I would imagine you know how that looks and because I forgot to screenshot that)

While it's blinking like this it seems like some items are duped at some point, some (or maybe all) items from the right side of the chests disappear.

I've replicated the behavior in creative using only 4 double chests and using 2 and 4 inventory connectors and even disconnecting both sides.

So far in my testing I have found that if you use single chests this bug doesn't occur with single chests, only with double chests.
In my setup I would guess that it's just that this bug because of the way this mod reads chests it would read the right part and left part separately and I guess the bug isn't fully consistent as in the timing of the flashing of the items therefore the two parts are desynced and that's what's causing the extra state of only one part working sometimes.


Here's also the list of my mods:
```appleskin-fabric-mc1.21-3.0.2
architectury-13.0.4-fabric
balm-fabric-1.21-21.0.14
betterstats-3.12.4+fabric-1.21
BetterThanMending-fabric-2.1.0
collective-1.21.0-7.71
CraftPresence-2.4.3+1.21
DetailArmorBar-2.6.3+1.21-fabric
Essential Dependencies
essential_1-3-2-8_fabric_1-21
EuphoriaPatcher-0.3.4-fabric
fabric-api-0.100.7+1.21
fabric-language-kotlin-1.11.0+kotlin.2.0.0
FallingTree-1.21-1.21.0.6
fullbrightnesstoggle-1.21.0-4.1
indium-1.0.34+mc1.21
iris-1.7.3+mc1.21
Jade-1.21-Fabric-15.1.4
journeymap-fabric-1.21-6.0.0-beta.18
libIPN-fabric-1.21-6.0.0
lithium-fabric-mc1.21-0.12.7
midnightlib-fabric-1.5.7
modernfix-fabric-5.18.8+mc1.21
modmenu-11.0.1
optigui-2.3.0-beta.2+1.21
placeholder-api-2.4.1+1.21
reeses_sodium_options-1.7.3+mc1.21
sodium-extra-0.5.7+mc1.21
sodium-fabric-0.5.11+mc1.21
tcdcommons-3.12.2+fabric-1.21
toms_storage_fabric-1.21-2.0.7
```
