### ISSUE TITLE
Item quantities in terminal are displayed as double what the actual quantity is

### ISSUE THREAD

**Issue by Erabior** [tom5454/Toms-Storage#69]
I'm using your mod with the extended storage mod (a better version of iron chests). essentially the major difference is in expanded storage upgraded chests can merge together to create upgraded double chests. I'm noticing that if there are upgraded double chests in the storage network, the item quantities are displayed as double the actual amount for all items within just the double chest. this only occur if the network is using inventory connectors. Video of bug coming momentarily......

**Comment by Erabior** [comment]
link to video: https://youtu.be/G-sWdhqetzc

**Comment by ffuentesm** [comment]
I actually have the same problem, from what I see, is the inventory connector. 
Inventory connector multiply item view in the terminal by the number of blocks making up the connected storage. 
In this example, I am using the new Create Vault Storage.
 I have a 2x2x3 vault, so 12 blocks, so all item amounts are multiplied by 12.
![image](https://user-images.githubusercontent.com/44974827/145542408-4d770aee-ac4b-46b7-a51a-319983a6b904.png)
![image](https://user-images.githubusercontent.com/44974827/145542416-18125916-38e4-4c3a-9810-623c1a24a652.png)
![image](https://user-images.githubusercontent.com/44974827/145542425-bed3f0c6-18bd-486c-b2e3-48395cf49f03.png)

**Comment by JasonTheCPE** [comment]
I'm having the same issue on Another Quality Modpack 2 - 1.18.1 | 1.17.1 (v1.4.1). I haven't looked at the code nor have experience in multiblock inventories for Minecraft but I would guess that it is treating every block of a connected inventory as its own inventory even though their contents are accessible through each other, hence the multiplied amount.

Partial solution would be to only access the inventory via the side touching the connector rather than getting information about the entire connected inventory. This would still cause issues if there was more than one connector touching a multiblock storage but it would work aside from that. A better solution might be to do the above but also get information on the blocks composing the full connected inventory and filter out accessing that inventory through anything but a single connector side if it does share multiple sides with a connector or is connected to multiple.

**Comment by ZakkiOrichalcum** [comment]
I am also seeing this issue with Drawers on 1.18.2 (the Drawers are being used with a Controller)

**Comment by e-SonOfAnder** [comment]
Reporting from version 1.3.4 of Toms Storage:
Same issue happens with Functional Storage (a variant of Storage Drawers), but only when accessed via the Controller block. If just the drawers are available via adjacent inventories, the count is correct. I suspect this is because it is counting the Controller as an inventory, and then all of the adjacent drawers as well causing a duplicate count.

Functional Storage allows for the controller to be placed non adjacent to the drawers it controls; by removing the physical adjacency between the controller and the drawers, and having the Tom's Storage inventory connector or adjacent storage only touching the controller, the counts are correct as well.

Tom's Storage _usually_ does the right thing and will insert into a storage drawer that holds an item before attempting to put more of it into a different location making it not completely necessary to use the Controller as the access point.

**Comment by Shadowex3** [comment]
Storage Drawers also appears to cause an internal multiplication by 3 when using the compacting drawers because Tom's sees each Compacting Drawer as 3 separate drawers each containing the full quantity of each item.

**Comment by tom5454** [comment]
Should be fixed in the latest versions on 1.18 and 1.19
