### ISSUE TITLE
Minecolonies integration issue

### ISSUE THREAD

**Issue by VerserVarlin** [tom5454/Toms-Storage#89]
in the mod pack, all the mods 7 when you place an inventory connector next to or on top of the warehouse control block from the mod minecolonies the inventory will repeatedly flash on the storage terminal for a second and goes away. this behavior is not to with the mod refined storage as it will work as normal.

if I use the inventory cable connectors on the individual item racks and do not have the inventory connector touching the warehouse control block the inventory displays correctly. this is not an ideal setup as the more connections I have to make the higher the server load is and it looks ugly. I will be posting this to all the mods 7 bug reporting site in the event it is their mod and not just some api issue.

**Comment by Zamokar** [comment]
I also have this issue on 1.18.2-1.3.4. I found a workaround by putting a crafting terminal directly on the warehouse block instead of an inventory connector, after which it works to access the warehouse inventory as expected.

**Comment by tom5454** [comment]
Should be fixed in the latest versions

**Comment by ZestyPurple4562** [comment]
I am having what I believe to be the same issue on 1.18.2-1.6.2 with MineColonies 1.18.2-1.0.1130-ALPHA.
Attaching a terminal directly to the warehouse block works perfectly, but using an inventory connector causes the inventory contents to appear missing, only flashing every couple seconds.

I suspected the problem was related to a storage rack being directly adjacent to the warehouse block, so I tried both directly connecting to the warehouse block with an inventory cable connector (with a dummy inventory connector not touching a storage inline) and destroying the adjacent rack; however, both of these resulted in no items displaying at all.

Connecting the inventory connector only to the racks with trim seems to work, but any of the (immovable) racks that touch the warehouse block must be excluded.

P.S. Thank you for making this amazing mod<3
